# Site settings
title: "Jimmy Mayoukou"
url: https://bhullnatik.github.io
description: "Jimmy Mayoukou Quick Summary"
keywords: "mobile,developer,android,react-native,freelance,hire,french,mayouk"

author:
  name: Jimmy Mayoukou
  email: Bhullnatik@gmail.com
  thumb: /images/author.JPG

social:
  - title: twitter
    url: https://twitter.com/bhullnatik
  - title: stack-overflow
    url: https://stackoverflow.com/story/bhullnatik
  - title: linkedin
    url: https://www.linkedin.com/in/bhullnatik/
  - title: github
    url: https://github.com/bhullnatik

# Build settings
markdown: kramdown
permalink: pretty
